services:
  pgo:
    container_name: pgo-apache2
    image: mkrlenron/lenron-pgo:0.5
    restart: always
    secrets: # Give access to these particular secrets to this container. This will mount the files to /run/secrets
      - email_creds
      - mariadb_root_pw
      - mariadb_login
      - mariadb_pw
    # Uncomment port on if accessing through localhost, which includes the simple cloudflare tunnel -> pgo setup.
    #ports:
      #- "80:80"
    volumes:
      - type: bind
        source: ./htdocs
        target: /usr/local/apache2/htdocs
      - type: bind
        source: ./logs
        target: /usr/local/apache2/logs
      - type: bind
        source: ./.htpasswd
        target: /usr/local/apache2/.htpasswd
      # This is the unix socket connection between apache and mariadb
      - type: bind
        source: /tmp/mysqld
        target: /run/mysqld
    depends_on:
      - mariadb-database
    networks:
      - proxy

  mariadb-database:
    container_name: pgo-mariadb
    image: mariadb:12.0.2
    restart: always
    secrets: # Give access to these particular secrets to this container. This will mount the files to /run/secrets
      - mariadb_root_pw
      - mariadb_login
      - mariadb_pw
    environment:
      # By appending file, tell docker to set 
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_pw
      MARIADB_USER_FILE: /run/secrets/mariadb_login
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_pw
      MARIADB_DATABASE: chatriwe_obf
    volumes:
      # .sql script that runs at container creation: creates SQL tables, events, etc.
      # Won't run if there is an existing mariadb_data volume.
      - ./mariadb_setup_files/obf.sql:/docker-entrypoint-initdb.d/obf.sql
      # Enable event_scheduler and set other configuration.
      - ./mariadb_setup_files/my.cnf:/etc/mysql/conf.d/my.cnf
      # Persist this volume which contains the database data.
      - mariadb_data:/var/lib/mysql
      # This is the socket connection between apache and mariadb.
      - /tmp/mysqld:/var/run/mysqld
    networks:
      - proxy

volumes: # This volume which contains the database data will persist.
  mariadb_data:
    name: mariadb_data

networks:
  proxy:
    name: proxy
    external: true # Setting up main, backup servers so that this never needs to be commented in this file.

secrets: # Declare files to be treated as secrets.
  mariadb_root_pw:
    file: ./secrets/mariadb_root_pw
  mariadb_login:
    file: ./secrets/mariadb_login
  mariadb_pw:
    file: ./secrets/mariadb_pw
  email_creds:
    file: ./secrets/email_creds







