services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - proxy
    environment:
      - TUNNEL_TOKEN=<TUNNEL TOKEN HERE>

networks:
  proxy:
    name: proxy
    external: true
